Fix changeserver 'Cleanup' test
30x/transicator pull request #76
Opened 2017-04-22 22:54 UTC by apg-pk

The 'Cleanup' test malfunctions when 'since' param is '0.0.0'. Also, add
2 extra seconds for detecting cleanup because the ticker for changeserver
startCleanup() can be off by ~1 second

Additionally, wrap defer in anonymous func when inside for loop

2017-04-25 17:38 UTC, gbrail commented
Thanks for looking at this.

With the change, if I run the tests repeatedly against the same Postgres instance, I get test failures in the cleanup test with the output below (the output is much longer -- I can attach if you'd like)

Do we need an additional step to clean the cleanup?

To run this, I have a Postgres server running on my box (I use "docker run -d -P apigeelabs/transicator-postgres") and I use "make tests."

... Lots of repeated stuff...
Num changes: 0
URL: http://127.0.0.1:64431/changes?scope=clean&since=5.7aa07968.0
{
  "code": "SNAPSHOT_TOO_OLD",
  "error": "The client is operating on an old snapshot"
}
Num changes: 0
URL: http://127.0.0.1:64431/changes?scope=clean&since=5.7aa07968.0
{
  "code": "SNAPSHOT_TOO_OLD",
  "error": "The client is operating on an old snapshot"
}
Num changes: 0
URL: http://127.0.0.1:64431/changes?scope=clean&since=5.7aa07968.0
{
  "code": "SNAPSHOT_TOO_OLD",
  "error": "The client is operating on an old snapshot"
}
Num changes: 0

------------------------------
• Failure [2.663 seconds]
Changes API Tests
/Users/gregbrail/go/src/github.com/apigee-labs/transicator/changeserver/changes_api_test.go:627
  Cleanup [It]
  /Users/gregbrail/go/src/github.com/apigee-labs/transicator/changeserver/changes_api_test.go:598

  Timed out after 2.003s.
  Expected
      <bool>: false
  to be true

  /Users/gregbrail/go/src/github.com/apigee-labs/transicator/changeserver/changes_api_test.go:558

2017-04-26 00:04 UTC, gbrail requested changes
When I tried this on my Mac with a PG database that stayed up in between test runs, the tests worked the first time but failed after that with an error in "cleanup." Can you try that and see if it happens to you as well?

2017-04-27 01:17 UTC, apg-pk commented
I am able to reproduce the same error using both `make tests` and `ginkgo`. If I just run the Cleanup test alone (with `TEST_PG_URL=... ginkgo --focus="Clean" -v changeserver/`), it has no problems with multiple test runs, but running all changeserver tests (with `TEST_PG_URL=... ginkgo -v changeserver/`). Looks like there's a race somewhere.

2017-04-29 01:42 UTC, apg-pk commented
There appears to be some unusual behavior where a long poll test for scope *foo* ahead of Cleanup test can cause the wrong *firstSequence* to be returned for scope *clean* by changeserver API. This old *firstSequence* value breaks our test which is not expecting to get a SNAPSHOT_TOO_OLD on the first change.

Here's the relevant snippet of debug log. Note that the value of *firstSequence* is reused across test scopes:
```
URL: http://127.0.0.1:49530/changes?snapshot=6820:6820:&selector=foo&block=30
DEBU[0014] Receiving changes: scopes = [foo] since = 0.0.1 limit = 100
...
DEBU[0016] Received 1 changes
{
  "lastSequence": "0.a6a4fd8.0",
  "firstSequence": "0.a6a4dc8.0",
  "changes": [
    {
      "operation": 1,
      "table": "public.changeserver_test",
      "sequence": "0.a6a4fd8.0",
      "commitSequence": 174739416,
      "changeSequence": 174739288,
      "commitIndex": 0,
      "txid": 6820,
      "timestamp": 1493426714,
      "newRow": {
        "_change_selector": {
          "value": "foo",
          "type": 1043
        },
        "sequence": {
          "value": "1493426702",
          "type": 23
        }
      }
    }
  ]
}
Num changes: 1
New seq = 1493426702 last = 1493426702 orig = 1493426702
•SS
------------------------------
Changes API Tests
  Cleanup
  /Users/impk/work/go/src/github.com/apigee-labs/transicator/changeserver/changes_api_test.go:598
...
URL: http://127.0.0.1:49530/changes?scope=clean
...
DEBU[0016] Receiving changes: scopes = [clean] since = 0.0.1 limit = 100
...
DEBU[0016] Received 0 changes
{
  "lastSequence": "0.a6a4fd8.0",
  "firstSequence": "0.a6a4dc8.0",
  "changes": null
}
Num changes: 0
URL: http://127.0.0.1:49530/changes?scope=clean
DEBU[0016] Receiving changes: scopes = [clean] since = 0.0.1 limit = 100
DEBU[0016] Received 0 changes
{
  "lastSequence": "0.a6a4fd8.0",
  "firstSequence": "0.a6a4dc8.0",
  "changes": null
}
Num changes: 0
URL: http://127.0.0.1:49530/changes?scope=clean
DEBU[0016] Receiving changes: scopes = [clean] since = 0.0.1 limit = 100
DEBU[0016] Received 0 changes
{
  "lastSequence": "0.a6a4fd8.0",
  "firstSequence": "0.a6a4dc8.0",
  "changes": null
}
Num changes: 0
DEBU[0016] Inserted a batch of 1 changes
DEBU[0016] Got updated LSN 174739600
DEBU[0016] Updating server with last LSN 174739600
...
URL: http://127.0.0.1:49530/changes?scope=clean
DEBU[0016] Receiving changes: scopes = [clean] since = 0.0.1 limit = 100
DEBU[0016] Received 1 changes
{
  "lastSequence": "0.a6a5090.0",
  "firstSequence": "0.a6a4dc8.0",
  "changes": [
    {
      "operation": 1,
      "table": "public.changeserver_test",
      "sequence": "0.a6a5090.0",
      "commitSequence": 174739600,
      "changeSequence": 174739464,
      "commitIndex": 0,
      "txid": 6821,
      "timestamp": 1493426715,
      "newRow": {
        "_change_selector": {
          "value": "clean",
          "type": 1043
        },
        "sequence": {
          "value": "1493426703",
          "type": 23
        }
      }
    }
  ]
}
```

2017-04-29 01:54 UTC, apg-pk commented
Looks like **firstSequence** is deliberately global for the whole database, as defined for ChangeList:
```
type ChangeList struct {
	// The highest value for "Sequence" in the whole database. The
	// client may use this to understand when they are at the end of the list
	// of changes.
	LastSequence string `json:"lastSequence"`
	// The lowest value for "Sequence" in the whole database. The client
	// may use this to determine if they are at the beginning of the whole
	// change list and must request a new snapshot to get consistent data.
	FirstSequence string `json:"firstSequence"`
	// All the changes, in order of "commit sequence" and "commit index"
	Changes []Change `json:"changes"`
}
```
We should update the test to avoid using **firstSequence** for query param **since**. Instead we should inspect the changelist for the first change or omit the **since** param if we just want the available changes from the beginning.

2017-05-01 17:00 UTC, apg-pk commented
Tests pass for me now

2017-05-02 10:28 UTC, gbrail approved these changes

2017-05-02 10:28 UTC, gbrail commented
Works great. Rebasing and merging. Thanks!

2017-05-02 10:30 UTC, merged